# Generated by Django 2.1.7 on 2020-03-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('annual', 'Annual Leave'), ('paternity', 'Paternity Leave'), ('study', 'Study Leave')], default='annual', max_length=25, null=True),
        ),
    ]
