# Generated by Django 2.1.7 on 2020-03-07 15:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200307_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, default='', help_text='your biography,tell me something about yourself eg. inspirations ...', max_length=255, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('High School', 'High School'), ('Primary', 'Primary School'), ('Tertiary', 'Tertiary/University/Polytechnic/MA/PhD'), ('O-LEVEL', 'OLevel'), ('Other', 'Other')], default='Tertiary', help_text='highest educational standard ie. your highest level of schooling', max_length=20, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2540000000', help_text='Enter number with Country Code Eg. +2540000000', max_length=128, region=None, verbose_name='Phone Number (Example +254000000)'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='foccupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='moccupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Enter number with Country Code Eg. +2540000000', max_length=128, null=True, region=None, verbose_name='Spouse Phone Number (Example +254000000)'),
        ),
    ]
