# Generated by Django 2.1.7 on 2020-03-10 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0007_auto_20200308_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='upload image size less than 2.0MB', null=True, upload_to='media/profiles', verbose_name='Profile Image'),
        ),
    ]
